feature searchbar works
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_Preflix pull request #1
Opened 2024-04-15 14:25 UTC by axeljdev

feature searchbar works, css work in progress

2024-04-15 14:31 UTC, Yoann-Fortin requested changes

2024-04-15 14:31 UTC, Yoann-Fortin commented on client/src/components/SearchBar.jsx
> +      <input type="search" placeholder="Rechercher" onChange={handleChange} />
label and link is missing

2024-04-15 14:31 UTC, Yoann-Fortin commented on client/src/components/SearchBar.jsx
> +        </article>
title in figcaption will be better

2024-04-16 10:18 UTC, Yoann-Fortin approved these changes

2024-04-16 10:23 UTC, Sylvainlfe approved these changes

2024-04-16 10:24 UTC, Alice-Berthelot approved these changes

2024-04-16 10:25 UTC, axeljdev commented on client/src/components/SearchBar.jsx
> +        </article>
fixed

2024-04-16 10:25 UTC, axeljdev commented on client/src/components/SearchBar.jsx
> +      <input type="search" placeholder="Rechercher" onChange={handleChange} />
fixed

2024-04-16 14:38 UTC, merged