finito pipo
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_Preflix pull request #45
Opened 2024-04-29 12:07 UTC by axeljdev

2024-04-29 13:30 UTC, axeljdev commented on client/src/pages/Article.jsx
> +    movie.media_type || (movie.original_title ? "movie" : "tv");
movie.mediatype to delete

2024-04-29 13:30 UTC, axeljdev commented on client/src/pages/Home.jsx
> +    movie.media_type || (movie.original_title ? "movie" : "tv");
to delete movie.media_type

2024-04-29 13:32 UTC, Delgorithm approved these changes
So cool !

2024-04-29 14:48 UTC, Yoann-Fortin requested changes

2024-04-30 08:34 UTC, Yoann-Fortin approved these changes

2024-04-30 08:34 UTC, merged