add navbar
WildCodeSchool-2024-02/JS-bdx-0224-P2-projet_Preflix pull request #7
Opened 2024-04-18 14:10 UTC by axeljdev

2024-04-18 14:11 UTC, Alice-Berthelot approved these changes

2024-04-18 14:12 UTC, Delgorithm approved these changes

2024-04-19 15:41 UTC, Yoann-Fortin requested changes

2024-04-19 15:41 UTC, Yoann-Fortin commented on client/src/Navbar.css
> +    font-size: 8pt;
Points ? Why ?

2024-04-19 15:41 UTC, Yoann-Fortin commented on client/src/components/NavBar.jsx
> +  const getIconHome = () =>
With a switch will be better

2024-04-22 14:50 UTC, closed without merging